#!/bin/bash
# Environment Setup Script for Lakehouse SQLPilot
# This script helps you configure .env.dev for running all tests

set -e

echo "🚀 Lakehouse SQLPilot - Environment Setup"
echo "=========================================="
echo ""

ENV_FILE=".env.dev"

# Check if .env.dev already exists
if [ -f "$ENV_FILE" ]; then
    echo "⚠️  .env.dev already exists"
    read -p "Do you want to update it? (y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Setup cancelled"
        exit 1
    fi
    echo "📝 Backing up existing .env.dev to .env.dev.backup"
    cp "$ENV_FILE" "$ENV_FILE.backup"
fi

echo ""
echo "📋 Credential Setup Options:"
echo "1. Database Credential API (RECOMMENDED - auto-rotating)"
echo "2. Static Credentials (Quick test - manual rotation)"
echo "3. All Methods (Maximum resilience)"
echo ""
read -p "Choose option (1/2/3): " -n 1 -r OPTION
echo ""
echo ""

# Initialize env file with common settings
cat > "$ENV_FILE" << 'EOF'
# Lakehouse SQLPilot Environment Configuration
# Generated by setup script

# ========================================
# DATABRICKS WORKSPACE
# ========================================
EOF

if [[ $OPTION =~ ^[13]$ ]]; then
    echo "🔐 Database Credential API Setup"
    echo "================================"
    echo ""
    
    echo "📍 Step 1: Databricks Workspace Hostname"
    echo "   Example: your-workspace.cloud.databricks.com"
    echo "   (without https://)"
    read -p "   Enter hostname: " DB_HOST
    
    echo ""
    echo "🔑 Step 2: Databricks Personal Access Token"
    echo "   Get from: Databricks → Settings → Developer → Access Tokens"
    echo "   Starts with: dapi..."
    read -p "   Enter token: " DB_TOKEN
    
    cat >> "$ENV_FILE" << EOF
DATABRICKS_SERVER_HOSTNAME="$DB_HOST"
DATABRICKS_TOKEN="$DB_TOKEN"
EOF
    echo "✅ Database Credential API configured"
    echo ""
fi

echo "🗄️  Lakebase Connection Setup"
echo "============================="
echo ""

echo "📍 Lakebase Host"
echo "   Example: instance-xxx.database.cloud.databricks.com"
read -p "   Enter Lakebase host: " LAKEBASE_HOST

echo ""
echo "📊 Lakebase Database Name"
read -p "   Enter database name [sqlpilot_state]: " LAKEBASE_DB
LAKEBASE_DB=${LAKEBASE_DB:-sqlpilot_state}

cat >> "$ENV_FILE" << EOF

# ========================================
# LAKEBASE (PostgreSQL for State)
# ========================================
LAKEBASE_HOST="$LAKEBASE_HOST"
LAKEBASE_DATABASE="$LAKEBASE_DB"
LAKEBASE_PORT="5432"
EOF

if [[ $OPTION =~ ^[23]$ ]]; then
    echo ""
    echo "🔐 Static Credentials Setup"
    echo "==========================="
    echo ""
    
    echo "👤 Lakebase Username"
    read -p "   Enter username: " LAKEBASE_USER
    
    echo ""
    echo "🔑 Lakebase Password"
    read -s -p "   Enter password: " LAKEBASE_PASSWORD
    echo ""
    
    cat >> "$ENV_FILE" << EOF

# Static Credentials (fallback)
LAKEBASE_USER="$LAKEBASE_USER"
LAKEBASE_PASSWORD="$LAKEBASE_PASSWORD"
EOF
    echo "✅ Static credentials configured"
    echo ""
fi

# Optional: SQL Warehouse for UAT tests
echo ""
read -p "📊 Configure SQL Warehouse for UAT tests? (y/n): " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "🏢 SQL Warehouse ID"
    echo "   Get from: Databricks → SQL Warehouses → Your Warehouse → Connection Details"
    read -p "   Enter warehouse ID: " WAREHOUSE_ID
    
    cat >> "$ENV_FILE" << EOF

# ========================================
# DATABRICKS SQL WAREHOUSE (for UAT)
# ========================================
DATABRICKS_WAREHOUSE_ID="$WAREHOUSE_ID"
EOF
    echo "✅ SQL Warehouse configured"
fi

# Add standard settings
cat >> "$ENV_FILE" << 'EOF'

# ========================================
# UNITY CATALOG
# ========================================
DATABRICKS_CATALOG="lakehouse-sqlpilot"
DATABRICKS_SCHEMA="lakehouse-sqlpilot-schema"

# ========================================
# SECURITY SETTINGS
# ========================================
SQLPILOT_REQUIRE_AUTH=false
SQLPILOT_SECRET_KEY="dev-secret-key-change-in-production"
SQLPILOT_API_KEYS=""

# Rate Limiting
SQLPILOT_RATE_LIMIT_ENABLED=true
SQLPILOT_RATE_LIMIT_REQUESTS=100
SQLPILOT_RATE_LIMIT_WINDOW=60

# Failed Auth Tracking
SQLPILOT_MAX_FAILED_AUTH=5
SQLPILOT_FAILED_AUTH_WINDOW=300

# CORS Origins (comma-separated)
SQLPILOT_ALLOWED_ORIGINS="http://localhost:5173,http://localhost:8080"

# Request Size Limit (bytes)
SQLPILOT_MAX_REQUEST_SIZE=10485760

# Audit Logging
SQLPILOT_AUDIT_LOG_ENABLED=false

# Environment
SQLPILOT_ENV="development"
EOF

echo ""
echo "✅ Configuration complete!"
echo ""
echo "📄 Created: $ENV_FILE"
echo ""
echo "🧪 Testing configuration..."
echo ""

# Source the file
set -a
source "$ENV_FILE"
set +a

# Test configuration
python3 << 'PYTHON_TEST'
import os
import sys

print("🔍 Validating configuration...\n")

errors = []
warnings = []

# Check Lakebase
if not os.getenv("LAKEBASE_HOST"):
    errors.append("LAKEBASE_HOST is required")
else:
    print(f"✅ Lakebase Host: {os.getenv('LAKEBASE_HOST')}")

# Check credential methods
db_api = os.getenv("DATABRICKS_SERVER_HOSTNAME") and os.getenv("DATABRICKS_TOKEN")
static = os.getenv("LAKEBASE_USER") and os.getenv("LAKEBASE_PASSWORD")

if db_api:
    print(f"✅ Database Credential API: Configured")
    print(f"   Host: {os.getenv('DATABRICKS_SERVER_HOSTNAME')}")
else:
    warnings.append("Database Credential API not configured")

if static:
    print(f"✅ Static Credentials: Configured")
    print(f"   User: {os.getenv('LAKEBASE_USER')}")
else:
    warnings.append("Static credentials not configured")

if not db_api and not static:
    errors.append("At least one credential method must be configured")

# Check SQL Warehouse
if os.getenv("DATABRICKS_WAREHOUSE_ID"):
    print(f"✅ SQL Warehouse: {os.getenv('DATABRICKS_WAREHOUSE_ID')}")
else:
    warnings.append("SQL Warehouse not configured (UAT tests will be skipped)")

print()

if warnings:
    print("⚠️  Warnings:")
    for w in warnings:
        print(f"   - {w}")
    print()

if errors:
    print("❌ Errors:")
    for e in errors:
        print(f"   - {e}")
    sys.exit(1)

print("✅ Configuration is valid!\n")

# Try to initialize smart credential manager
try:
    from infrastructure.smart_credentials import get_smart_credential_manager
    manager = get_smart_credential_manager()
    methods = manager.get_available_methods()
    print(f"📋 Available credential methods: {', '.join(methods)}")
    
    # Try to get credentials
    try:
        username, password = manager.get_credentials()
        method = manager.get_last_successful_method()
        print(f"✅ Successfully obtained credentials via: {method}")
        print(f"   Username: {username[:20]}...")
    except Exception as e:
        print(f"⚠️  Could not obtain credentials: {e}")
        print("   This may be normal if Databricks/Lakebase is not accessible")
        
except Exception as e:
    print(f"⚠️  Note: {e}")

PYTHON_TEST

if [ $? -eq 0 ]; then
    echo ""
    echo "🎉 Setup Complete!"
    echo ""
    echo "📋 Next Steps:"
    echo "1. Load environment: source .env.dev"
    echo "2. Run tests:        pytest tests/ -v"
    echo "3. Run specific:     pytest tests/test_lakebase_backend.py -v"
    echo ""
    echo "📚 Documentation:"
    echo "   - Full guide:     docs/TESTING_BLOCKED_TESTS_GUIDE.md"
    echo "   - Quick start:    docs/QUICK_START_AUTO_REFRESH.md"
    echo ""
else
    echo ""
    echo "❌ Setup failed. Please fix errors and try again."
    echo ""
    exit 1
fi


