"""
Base Agent - Abstract base class for all SQLPilot agents
"""

from abc import ABC, abstractmethod
from typing import Dict, Any, List
from datetime import datetime, timezone
import uuid


class AgentBoundaryViolation(Exception):
    """Exception raised when agent violates boundaries"""
    pass


class BaseAgent(ABC):
    """Abstract base class for all SQLPilot agents"""
    
    # Forbidden operations for ALL agents
    FORBIDDEN_OPERATIONS = [
        'execute_sql',
        'modify_tables',
        'drop_tables',
        'grant_permissions',
        'deploy_to_production',
        'auto_fix_errors',
        'bypass_validation',
    ]
    
    def __init__(self, name: str, description: str):
        """
        Initialize base agent
        
        Args:
            name: Agent name
            description: Agent description
        """
        self.name = name
        self.description = description
        self.interaction_log = []
    
    @abstractmethod
    def process(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Process agent input and return output
        
        Args:
            input_data: Input dictionary
            
        Returns:
            Output dictionary with suggestions/results
        """
        pass
    
    @abstractmethod
    def get_allowed_inputs(self) -> List[str]:
        """Get list of allowed input types"""
        pass
    
    @abstractmethod
    def get_allowed_outputs(self) -> List[str]:
        """Get list of allowed output types"""
        pass
    
    def log_interaction(self, input_data: Dict[str, Any], output_data: Dict[str, Any]) -> None:
        """
        Log agent interaction
        
        Args:
            input_data: Input provided to agent
            output_data: Output generated by agent
        """
        self.interaction_log.append({
            'interaction_id': str(uuid.uuid4()),
            'agent_name': self.name,
            'timestamp': datetime.now(timezone.utc).isoformat(),
            'input': input_data,
            'output': output_data
        })
    
    def enforce_boundaries(self, operation: str) -> None:
        """
        Enforce agent boundaries
        
        Args:
            operation: Operation being attempted
            
        Raises:
            AgentBoundaryViolation: If operation is forbidden
        """
        if operation in self.FORBIDDEN_OPERATIONS:
            raise AgentBoundaryViolation(
                f"Agent {self.name} attempted forbidden operation: {operation}"
            )
    
    def validate_input(self, input_data: Dict[str, Any]) -> tuple[bool, List[str]]:
        """
        Validate input data
        
        Args:
            input_data: Input to validate
            
        Returns:
            Tuple of (is_valid, list_of_errors)
        """
        errors = []
        
        # Check required fields
        if 'request_type' not in input_data:
            errors.append("Missing required field: request_type")
        
        # Check if request type is allowed
        request_type = input_data.get('request_type')
        if request_type and request_type not in self.get_allowed_inputs():
            errors.append(f"Request type '{request_type}' not allowed for agent {self.name}")
        
        return len(errors) == 0, errors

